# Generated by Django 3.2.3 on 2021-05-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=700)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nasa_jpl_url', models.URLField()),
                ('is_potentially_hazardous_asteroid', models.BooleanField(default=False)),
                ('element_count', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
