# Generated by Django 3.2.3 on 2021-05-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neo',
            name='neo_instance_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='neo',
            name='element_count',
            field=models.IntegerField(default=0),
        ),
    ]
