# Generated by Django 3.2.3 on 2021-05-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210519_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neo',
            name='name',
            field=models.CharField(default='', max_length=700, unique=True),
        ),
        migrations.AlterField(
            model_name='neo',
            name='nasa_jpl_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='neo',
            name='neo_instance_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
