# Generated by Django 3.2.3 on 2021-05-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210520_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neo',
            name='element_count',
        ),
    ]
