# Generated by Django 3.2.3 on 2021-05-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_neo_element_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neo',
            old_name='neo_instance_id',
            new_name='neo_reference_id',
        ),
    ]
